### ISSUE TITLE
Good Locations for Farming/Botting

### ISSUE THREAD

**Issue by Novalys** [Novalys/PokemonGo-Bot-SimpleGUI#17]
Hello, the new feature to use a map to select the starting location provides a list of good locations, if anyone has good locations that can be added it would be really helpful.

**Comment by darkhax** [comment]
Here are a few pokevision links to various hotspots. Depending on the time of day, these areas can be completely covered. They should also help cover the regional exclusives. 
- [Santa Monica Pier, Las Angeles, USA](https://pokevision.com/#/@34.00873594425199,-118.49761247634888)
- [Bryant Park, New York, USA](https://pokevision.com/#/@40.75320648472645,-73.98390769958496)
- [Sydney, Australia](https://pokevision.com/#/@-33.870273020353416,151.20878219604492)
- [Tokyo, Japan](https://pokevision.com/#/@35.69051125265253,139.68954205513)

**Comment by Novalys** [comment]
Thanks for the locations @darkhax they have been added.

**Comment by pavelmoulisjr** [comment]
For regional exclusives that @darkhax mentioned -- whilst they seem to spawn completely randomly, at least based on some location scans I did around Europe (Mime is completely unpredictable), any populated area should do.

I've had high success with Tauros (North America) at 45.030011, -93.319311 (Minneapolis), probably because that spot is so heavily populated by Nox users macroing the 6 pokestops.
In Asia, I've consistently seen at least 2 Farfetch'd per day in Sokcho (South Korea), though their location varied greatly.

**Comment by darkhax** [comment]
@Novalys How about storing these locations in an editable file. This would be much more flexible and allow users to edit and share locations easier.

**Comment by Wyn10** [comment]
```
comboLocations.Items.Add(new Loc() { name = "Confederation Park, Ottawa", lat = 45.422124, lng = -75.692401 });
```

```
comboLocations.Items.Add(new Loc() { name = "Parliament, Ottawa", lat = 45.423782, lng = -75.698742 });
```
