### ISSUE TITLE
Shortban when receiving 0XP from Pokestops?

### ISSUE THREAD

**Issue by nxy** [Novalys/PokemonGo-Bot-SimpleGUI#36]
I think there's a shortban everytime when the bot fails to receive XP from Pokestops, because I noticed afterwards that pokemon would instantly run away (shortban only lasts 20 seconds or so?). If this is indeed the case, anyway to avoid it?

**Comment by UncleMart** [comment]
It's actually the other way around, the bot is failing to receive XP and losing pokemon because you have a soft ban ;) It's likely because you or the bot have moved too far in a short amount of time. This mostly happens because of using GPS coords that are very different while (re)starting the bot or game on your device.

**Comment by nxy** [comment]
That can't be. I've been in the same spot 2+ hours already. I already set the default longitude/latitude inside the config file.
